### ISSUE TITLE
Yanking and Pasting to and from system clipboard not working in MacOS

### ISSUE THREAD

**Issue by brauliomartinezlm** [cedarcode/cedarvim#30]
Copying and Pasting using system clipboard is not working correctly in MacOS

Versions:
- Vim 8.0.642
- MacOS 10.13.3

**Comment by grzuy** [comment]
Related resource:

* https://github.com/vim/vim/issues/2528

**Comment by brauliomartinezlm** [comment]
I found that mi problem was that during installation, my Vim wasn't compiled with +clipboard, and I think that's pretty much it.

I don't think mac clipboard issues during vim compilation is something that I would expect this Vim distribution would help anyone solve. Thus, I'm closing this issue. There's no possible configuration here that could avoid the issue I had.

Thanks for the reference, that was useful reading (I solved it similarly some months ago but wo reading anything like this, would have been useful :) )!

**Comment by grzuy** [comment]
Fixed by #38
